application: szybkafucha
version: 1-54
api_version: 1
runtime: python

handlers:
- url: /
  script: main.py

- url: /index\.html
  script: main.py

- url: /gfx
  static_dir: gfx

- url: /css
  static_dir: css

- url: /scripts
  static_dir: scripts

- url: /mp3
  static_dir: mp3

- url: /swf
  static_dir: swf

- url: /pdf
  static_dir: pdf

- url: /task_add\.html
  script: task_add.py  
  
- url: /task_confirm\.html
  script: task_confirm.py  
  
- url: /tasks_view\.html
  script: tasks_view.py  
  
- url: /client_login\.html
  script: client_login.py

- url: /client_confirm\.html
  script: client_confirm.py

- url: /client_activate\.html
  script: client_activate.py

- url: /client_remind\.html
  script: client_remind.py

- url: /client_profile\.html
  script: client_profile.py

- url: /student_login\.html
  script: student_login.py

- url: /student_confirm\.html
  script: student_confirm.py

- url: /student_activate\.html
  script: student_activate.py

- url: /student_remind\.html
  script: student_remind.py

- url: /student_profile\.html
  script: student_profile.py

- url: /avatar\.png
  script: avatar.py
  
- url: /logout\.html
  script: logout.py
  
- url: /law\.html
  script: law.py

- url: /commercials\.html
  script: commercials.py

- url: /help\.html
  script: help.py

- url: /rules\.html
  script: rules.py

- url: /fill_db1\.html
  script: fill_db1.py

- url: /fill_db2\.html
  script: fill_db2.py

- url: /fill_db3\.html
  script: fill_db3.py

- url: /fill_db4\.html
  script: fill_db4.py

- url: /fill_db5\.html
  script: fill_db5.py

- url: /.*
  script: not_found.py
