#!/usr/bin/env python
# -*- coding: utf-8 -*-
from google.appengine.dist import use_library
use_library('django', '1.2')

import wsgiref.handlers
from google.appengine.ext import webapp
from google.appengine.ext.webapp import template
from db_scheme import *

class MainHandler(webapp.RequestHandler):
	def get(self):
		voivodeship = Voivodeship(name=u'podlaskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Białystok', people=295198)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Suwałki', people=69527)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łomża', people=63221)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Augustów', people=30351)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bielsk Podlaski', people=26349)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zambrów', people=22314)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Grajewo', people=22239)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Hajnówka', people=21444)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sokółka', people=18532)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łapy', people=16049)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Siemiatycze', people=14810)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kolno', people=10486)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mońki', people=10352)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wasilków', people=9753)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czarna Białostocka', people=9512)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wysokie Mazowieckie', people=9333)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dąbrowa Białostocka', people=5928)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sejny', people=5707)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Choroszcz', people=5469)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ciechanowiec', people=4914)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Supraśl', people=4606)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brańsk', people=3751)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczuczyn', people=3496)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Michałowo', people=3373)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czyżew', people=2755)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Knyszyn', people=2744)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krynki', people=2573)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zabłudów', people=2485)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lipsk', people=2424)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stawiski', people=2350)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szepietowo', people=2305)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Suchowola', people=2186)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowogród', people=2085)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Drohiczyn', people=2031)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Goniądz', people=1939)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jedwabne', people=1924)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tykocin', people=1919)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rajgród', people=1707)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kleszczele', people=1388)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Suraż', people=1007)
		city.put()

		voivodeship = Voivodeship(name=u'pomorskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gdańsk', people=456967)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gdynia', people=247324)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Słupsk', people=96655)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tczew', people=60152)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Starogard Gdański', people=48185)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wejherowo', people=47794)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rumia', people=46107)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chojnice', people=39919)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kwidzyn', people=38296)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Malbork', people=38278)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sopot', people=38141)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lębork', people=34581)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pruszcz Gdański', people=26834)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kościerzyna', people=23138)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Reda', people=20959)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bytów', people=16650)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ustka', people=16062)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Władysławowo', people=15111)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kartuzy', people=14922)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Człuchów', people=14189)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Puck', people=11249)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miastko', people=10695)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowy Dwór Gdański', people=9904)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sztum', people=9676)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czersk', people=9673)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Prabuty', people=8573)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pelplin', people=8244)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skarszewy', people=6881)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gniew', people=6709)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żukowo', people=6519)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czarne', people=5938)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dzierzgoń', people=5522)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Debrzno', people=5357)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brusy', people=4825)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowy Staw', people=4367)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jastarnia', people=3911)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łeba', people=3753)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kępice', people=3750)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Hel', people=3720)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skórcz', people=3591)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czarna Woda', people=3211)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krynica Morska', people=1361)
		city.put()

		voivodeship = Voivodeship(name=u'warmińsko-mazurskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Olsztyn', people=176463)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Elbląg', people=126049)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ełk', people=57897)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostróda', people=33187)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Iława', people=32343)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Giżycko', people=29304)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kętrzyn', people=27515)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczytno', people=24908)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bartoszyce', people=24721)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mrągowo', people=21712)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Działdowo', people=20922)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pisz', people=19439)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Braniewo', people=17457)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lidzbark Warmiński', people=16209)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Olecko', people=16078)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nidzica', people=14337)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Morąg', people=13895)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gołdap', people=13401)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pasłęk', people=12067)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Węgorzewo', people=11377)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowe Miasto Lubawskie', people=11061)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobre Miasto', people=10440)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biskupiec', people=10329)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubawa', people=9661)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Orneta', people=9145)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lidzbark', people=8131)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Olsztynek', people=7565)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Barczewo', people=7309)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Orzysz', people=5732)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Susz', people=5578)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Reszel', people=4898)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ruciane-Nida', people=4633)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Korsze', people=4448)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Górowo Iławeckie', people=4419)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biała Piska', people=3952)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mikołajki', people=3734)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jeziorany', people=3320)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ryn', people=2963)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pieniężno', people=2801)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tolkmicko', people=2724)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miłakowo', people=2692)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pasym', people=2549)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bisztynek', people=2436)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Frombork', people=2425)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miłomłyn', people=2347)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kisielice', people=2210)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zalewo', people=2079)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sępopol', people=2013)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Młynary', people=1776)
		city.put()

		voivodeship = Voivodeship(name=u'wielkopolskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Poznań', people=551627)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kalisz', people=106664)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Konin', people=79212)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piła', people=74550)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostrów Wielkopolski', people=72382)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gniezno', people=69483)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Leszno', people=64432)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Swarzędz', people=30487)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Śrem', people=29895)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Luboń', people=29520)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krotoszyn', people=29485)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Września', people=29157)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Turek', people=28531)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jarocin', people=26029)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wągrowiec', people=25083)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kościan', people=24084)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koło', people=22861)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Środa Wielkopolska', people=22179)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rawicz', people=21054)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gostyń', people=20459)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chodzież', people=19506)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szamotuły', people=18878)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Złotów', people=18303)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Oborniki', people=18034)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pleszew', people=17530)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzcianka', people=16894)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowy Tomyśl', people=14865)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kępno', people=14682)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostrzeszów', people=14369)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Grodzisk Wielkopolski', people=13999)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Słupca', people=13946)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wolsztyn', people=13393)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mosina', people=12454)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wronki', people=11443)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czarnków', people=11194)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rogoźno', people=11158)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzychód', people=10844)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Murowana Goślina', people=10323)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Puszczykowo', people=9635)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Opalenica', people=9362)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kostrzyn', people=9041)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pobiedziska', people=8748)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jastrowie', people=8485)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Witkowo', people=7943)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pniewy', people=7829)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzemeszno', people=7807)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zbąszyń', people=7211)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kórnik', people=7210)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kłodawa', people=6707)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koźmin Wielkopolski', people=6678)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krzyż Wielkopolski', people=6269)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sieraków', people=6091)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Buk', people=6089)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wieleń', people=5869)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stęszew', people=5686)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Śmigiel', people=5536)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wyrzysk', people=5232)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czempiń', people=5183)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Odolanów', people=5003)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowe Skalmierzyce', people=4922)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zduny', people=4514)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Golina', people=4398)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szamocin', people=4291)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kleczew', people=4232)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krobia', people=4089)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skoki', people=4003)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ujście', people=3874)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Okonek', people=3855)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krajenka', people=3659)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sompolno', people=3624)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miłosław', people=3581)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nekla', people=3398)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tuliszków', people=3373)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gołańcz', people=3333)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rakoniewice', people=3332)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pyzdry', people=3228)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ślesin', people=3200)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miejska Górka', people=3190)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kobylin', people=3130)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łobżenica', people=3043)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Margonin', people=2989)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zagórów', people=2985)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lwówek', people=2961)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bojanowo', people=2953)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sulmierzyce', people=2859)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Poniec', people=2851)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Książ Wielkopolski', people=2738)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wysoka', people=2736)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rydzyna', people=2700)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kłecko', people=2632)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czerniejewo', people=2598)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Borek Wielkopolski', people=2532)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rychwał', people=2364)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Obrzycko', people=2262)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Osieczna', people=2131)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żerków', people=2122)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Raszków', people=2080)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pogorzela', people=2037)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dąbie', people=2000)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostroróg', people=1962)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Grabów nad Prosną', people=1947)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jutrosin', people=1906)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mikstat', people=1835)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Przedecz', people=1772)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wielichowo', people=1746)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krzywiń', people=1634)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stawiszyn', people=1552)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dolsk', people=1528)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobra', people=1443)
		city.put()

		self.response.out.write(template.render('fill_db.html', {}))
	
def main():
	application = webapp.WSGIApplication([(r'.*', MainHandler)], debug=True)
	wsgiref.handlers.CGIHandler().run(application)

if __name__ == '__main__':
	main()
