#!/usr/bin/env python
# -*- coding: utf-8 -*-
from google.appengine.dist import use_library
use_library('django', '1.2')

import wsgiref.handlers
from google.appengine.ext import webapp
from google.appengine.ext.webapp import template
from db_scheme import *

class MainHandler(webapp.RequestHandler):
	def get(self):
		voivodeship = Voivodeship(name=u'zachodniopomorskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczecin', people=405606)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koszalin', people=107948)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stargard Szczeciński', people=69633)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kołobrzeg', people=44984)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świnoujście', people=40759)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczecinek', people=38977)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Police', people=33951)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wałcz', people=25942)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Białogard', people=24227)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Goleniów', people=22349)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gryfino', people=21249)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowogard', people=16816)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gryfice', people=16541)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Choszczno', people=15671)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świdwin', people=15487)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Barlinek', people=14085)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Darłowo', people=13954)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dębno', people=13862)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Złocieniec', people=13217)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sławno', people=13020)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pyrzyce', people=12693)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Myślibórz', people=11539)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Drawsko Pomorskie', people=11409)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łobez', people=10459)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzebiatów', people=10131)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kamień Pomorski', people=9094)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Połczyn-Zdrój', people=8372)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chojna', people=7374)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czaplinek', people=6897)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sianów', people=6555)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Karlino', people=5816)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzyzdroje', people=5479)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wolin', people=4842)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Borne Sulinowo', people=4675)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bobolice', people=4343)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Resko', people=4329)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kalisz Pomorski', people=4224)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lipiany', people=4048)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Płoty', people=4035)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Barwice', people=3713)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mieszkowice', people=3526)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Maszewo', people=3261)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chociwel', people=3226)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Węgorzyno', people=3005)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Recz', people=2963)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Polanów', people=2917)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dziwnów', people=2867)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Golczewo', people=2708)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pełczyce', people=2681)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mirosławiec', people=2671)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tychowo', people=2480)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzcińsko-Zdrój', people=2455)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gościno', people=2444)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Drawno', people=2382)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Człopa', people=2354)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobrzany', people=2339)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobra', people=2305)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biały Bór', people=2219)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ińsko', people=2026)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tuczno', people=1900)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Cedynia', people=1624)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Moryń', people=1622)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Suchań', people=1436)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowe Warpno', people=1237)
		city.put()

		voivodeship = Voivodeship(name=u'łódzkie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łódź', people=737098)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piotrków Trybunalski', people=77383)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pabianice', people=68550)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tomaszów Mazowiecki', people=65210)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bełchatów', people=60768)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zgierz', people=57900)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skierniewice', people=49044)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radomsko', people=48220)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kutno', people=46221)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zduńska Wola', people=43854)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sieradz', people=43286)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łowicz', people=29567)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wieluń', people=23731)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Opoczno', people=22685)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Aleksandrów Łódzki', people=20809)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ozorków', people=20189)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łask', people=18457)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Konstantynów Łódzki', people=17688)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rawa Mazowiecka', people=17508)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łęczyca', people=15113)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Głowno', people=14940)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koluszki', people=13399)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brzeziny', people=12309)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wieruszów', people=8595)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żychlin', people=8430)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zelów', people=7952)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Poddębice', people=7781)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tuszyn', people=7118)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pajęczno', people=6723)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sulejów', people=6418)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Działoszyn', people=6099)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krośniewice', people=4603)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Drzewica', people=3946)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Przedbórz', people=3721)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stryków', people=3530)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Złoczew', people=3449)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rzgów', people=3416)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Warta', people=3357)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biała Rawska', people=3101)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Uniejów', people=2922)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kamieńsk', people=2867)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wolbórz', people=2282)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Błaszki', people=2070)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szadek', people=2002)
		city.put()

		voivodeship = Voivodeship(name=u'śląskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Katowice', people=306826)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Częstochowa', people=238042)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sosnowiec', people=217638)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gliwice', people=195472)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zabrze', people=186913)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bytom', people=181617)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bielsko-Biała', people=175008)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ruda Śląska', people=142950)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rybnik', people=141410)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tychy', people=129386)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dąbrowa Górnicza', people=127431)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chorzów', people=112697)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jaworzno', people=94807)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jastrzębie-Zdrój', people=92462)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mysłowice', people=74865)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Siemianowice Śląskie', people=70291)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żory', people=61925)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tarnowskie Góry', people=60818)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Będzin', people=58584)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piekary Śląskie', people=58268)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Racibórz', people=56397)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świętochłowice', people=53798)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zawiercie', people=51695)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wodzisław Śląski', people=49000)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mikołów', people=39196)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Knurów', people=39154)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Cieszyn', people=35421)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czechowice-Dziedzice', people=35061)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czeladź', people=33415)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Myszków', people=32721)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żywiec', people=32056)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czerwionka-Leszczyny', people=28177)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pszczyna', people=25415)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubliniec', people=24125)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łaziska Górne', people=22113)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rydułtowy', people=21850)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bieruń', people=19519)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Orzesze', people=19304)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pyskowice', people=19067)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radlin', people=17767)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radzionków', people=17169)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lędziny', people=16396)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ustroń', people=15588)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skoczów', people=14666)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pszów', people=14041)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kłobuck', people=13085)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wisła', people=11233)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Blachownia', people=9865)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wojkowice', people=9136)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Poręba', people=8765)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kalety', people=8681)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Imielin', people=8264)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Miasteczko Śląskie', people=7355)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łazy', people=7133)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sławków', people=6945)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koniecpol', people=6201)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczyrk', people=5782)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kuźnia Raciborska', people=5485)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Siewierz', people=5436)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żarki', people=4563)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krzepice', people=4472)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ogrodzieniec', people=4401)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Woźniki', people=4384)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczekociny', people=3790)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Toszek', people=3511)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Strumień', people=3453)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wilamowice', people=2890)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koziegłowy', people=2456)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krzanowice', people=2176)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pilica', people=1992)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sośnicowice', people=1715)
		city.put()

		voivodeship = Voivodeship(name=u'świętokrzyskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kielce', people=203804)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostrowiec Świętokrzyski', people=71959)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Starachowice', people=51605)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skarżysko-Kamienna', people=47525)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sandomierz', people=24375)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Końskie', people=19962)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Busko-Zdrój', people=16742)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jędrzejów', people=16139)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Staszów', people=15108)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pińczów', people=11303)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Włoszczowa', people=10657)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Suchedniów', people=8635)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Połaniec', people=8227)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Opatów', people=6658)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sędziszów', people=6639)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stąporków', people=5848)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kazimierza Wielka', people=5575)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ożarów', people=4661)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chęciny', people=4304)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chmielnik', people=3891)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Małogoszcz', people=3849)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ćmielów', people=3176)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kunów', people=3040)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Daleszyce', people=2953)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wąchock', people=2744)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koprzywnica', people=2540)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bodzentyn', people=2223)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Osiek', people=2001)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zawichost', people=1813)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skalbmierz', people=1310)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Działoszyce', people=991)
		city.put()

		self.response.out.write(template.render('fill_db.html', {}))
	
def main():
	application = webapp.WSGIApplication([(r'.*', MainHandler)], debug=True)
	wsgiref.handlers.CGIHandler().run(application)

if __name__ == '__main__':
	main()
