#!/usr/bin/env python
# -*- coding: utf-8 -*-
from google.appengine.dist import use_library
use_library('django', '1.2')

import wsgiref.handlers
from google.appengine.ext import webapp
from google.appengine.ext.webapp import template
from db_scheme import *

class MainHandler(webapp.RequestHandler):
	def get(self):
		voivodeship = Voivodeship(name=u'dolnośląskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wrocław', people=632996)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wałbrzych', people=120197)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Legnica', people=103892)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jelenia Góra', people=84023)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubin', people=74045)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Głogów', people=67613)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świdnica', people=59384)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bolesławiec', people=39832)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Oleśnica', people=36998)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dzierżoniów', people=33943)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zgorzelec', people=31551)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Oława', people=31025)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bielawa', people=30775)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kłodzko', people=27709)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jawor', people=23773)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowa Ruda', people=23477)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świebodzice', people=22890)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Polkowice', people=22210)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubań', people=21562)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kamienna Góra', people=20444)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bogatynia', people=18591)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Strzegom', people=16517)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Złotoryja', people=16387)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Boguszów-Gorce', people=16064)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ząbkowice Śląskie', people=15830)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jelcz-Laskowice', people=15508)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chojnów', people=14328)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brzeg Dolny', people=12652)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzebnica', people=12460)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Góra', people=12364)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wołów', people=12302)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Strzelin', people=12113)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Milicz', people=11887)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kowary', people=11497)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Syców', people=10627)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bystrzyca Kłodzka', people=10298)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kudowa-Zdrój', people=10112)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pieszyce', people=9342)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lwówek Śląski', people=9299)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ziębice', people=9107)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Środa Śląska', people=8952)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Oborniki Śląskie', people=8577)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chocianów', people=8096)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sobótka', people=6924)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żarów', people=6879)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szklarska Poręba', people=6833)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Polanica-Zdrój', people=6827)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gryfów Śląski', people=6811)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Twardogóra', people=6797)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Głuszyca', people=6768)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piława Górna', people=6758)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żmigród', people=6519)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piechowice', people=6489)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Przemków', people=6372)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubawka', people=6277)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stronie Śląskie', people=6034)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lądek-Zdrój', people=5917)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pieńsk', people=5764)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ścinawa', people=5748)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kąty Wrocławskie', people=5678)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczawno-Zdrój', people=5598)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bolków', people=5295)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczytna', people=5185)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jaworzyna Śląska', people=5145)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jedlina-Zdrój', people=5057)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bierutów', people=5018)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Karpacz', people=4932)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Duszniki-Zdrój', people=4860)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Olszyna', people=4643)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Leśna', people=4562)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świeradów-Zdrój', people=4448)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mieroszów', people=4421)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Siechnice', people=4403)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zawidów', people=4301)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mirsk', people=4111)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowogrodziec', people=4025)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wojcieszów', people=3964)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Prochowice', people=3746)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Niemcza', people=3085)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Węgliniec', people=2923)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Złoty Stok', people=2879)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wąsosz', people=2762)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzylesie', people=2740)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bardo', people=2729)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radków', people=2414)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzybórz', people=2388)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świerzawa', people=2364)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wiązów', people=2327)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Prusice', people=2185)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubomierz', people=1838)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wleń', people=1838)
		city.put()

		voivodeship = Voivodeship(name=u'kujawsko-pomorskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bydgoszcz', people=356177)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Toruń', people=205312)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Włocławek', people=116914)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Grudziądz', people=98757)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Inowrocław', people=75802)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brodnica', people=27731)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świecie', people=25656)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chełmno', people=20104)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nakło nad Notecią', people=19148)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rypin', people=16528)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Solec Kujawski', people=15328)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chełmża', people=15102)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lipno', people=14764)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żnin', people=14020)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tuchola', people=13886)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wąbrzeźno', people=13877)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Golub-Dobrzyń', people=12935)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mogilno', people=12290)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Aleksandrów Kujawski', people=12275)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Koronowo', people=11029)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ciechocinek', people=10841)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szubin', people=9333)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kruszwica', people=9211)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sępólno Krajeńskie', people=9102)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Janikowo', people=9073)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Barcin', people=7702)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gniewkowo', people=7182)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowe', people=6104)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Strzelno', people=5899)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Więcbork', people=5813)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Pakość', people=5774)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radziejów', people=5696)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kcynia', people=4702)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Brześć Kujawski', people=4603)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łabiszyn', people=4452)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piotrków Kujawski', people=4391)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Mrocza', people=4368)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kowalewo Pomorskie', people=4115)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Janowiec Wielkopolski', people=4069)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jabłonowo Pomorskie', people=3686)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skępe', people=3529)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kowal', people=3488)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łasin', people=3266)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubraniec', people=3130)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Izbica Kujawska', people=2753)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kamień Krajeński', people=2344)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobrzyń nad Wisłą', people=2254)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nieszawa', people=1990)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radzyń Chełmiński', people=1891)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chodecz', people=1862)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Górzno', people=1357)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubień Kujawski', people=1298)
		city.put()

		voivodeship = Voivodeship(name=u'lubelskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lublin', people=348450)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Chełm', people=67324)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zamość', people=66234)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biała Podlaska', people=57984)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Puławy', people=48578)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świdnik', people=39851)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kraśnik', people=35262)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łuków', people=30373)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Biłgoraj', people=27235)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubartów', people=22545)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łęczna', people=20706)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tomaszów Lubelski', people=19802)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krasnystaw', people=19237)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Hrubieszów', people=18318)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dęblin', people=17549)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzyrzec Podlaski', people=17006)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Radzyń Podlaski', people=16017)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Włodawa', people=13402)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Janów Lubelski', people=11904)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Parczew', people=10048)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ryki', people=9557)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Poniatowa', people=9541)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Opole Lubelskie', people=8649)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bełżyce', people=6908)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Terespol', people=5901)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bychawa', people=5254)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szczebrzeszyn', people=5245)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rejowiec Fabryczny', people=4441)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nałęczów', people=4237)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kock', people=3452)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kazimierz Dolny', people=3414)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tarnogród', people=3362)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zwierzyniec', people=3353)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krasnobród', people=3136)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Stoczek Łukowski', people=2721)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Piaski', people=2663)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Annopol', people=2654)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Józefów', people=2376)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ostrów Lubelski', people=2225)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łaszczów', people=2192)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Tyszowce', people=2123)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Frampol', people=1413)
		city.put()

		voivodeship = Voivodeship(name=u'lubuskie')
		voivodeship.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gorzów Wielkopolski', people=125394)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zielona Góra', people=117699)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowa Sól', people=39796)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żary', people=38617)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Żagań', people=26253)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Świebodzin', people=21670)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Międzyrzecz', people=18472)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kostrzyn nad Odrą', people=17704)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sulechów', people=17517)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gubin', people=16631)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Słubice', people=16480)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubsko', people=14609)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Wschowa', people=14357)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szprotawa', people=12341)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Krosno Odrzańskie', people=11881)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Drezdenko', people=10193)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Strzelce Krajeńskie', people=10188)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sulęcin', people=10103)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Skwierzyna', people=10098)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kożuchów', people=9537)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Witnica', people=6859)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Rzepin', people=6487)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowogród Bobrzański', people=5106)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Zbąszynek', people=5042)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Bytom Odrzański', people=4496)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Jasień', people=4376)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Babimost', people=4196)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Czerwieńsk', people=4089)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Iłowa', people=3982)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Sława', people=3923)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Ośno Lubuskie', people=3812)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Kargowa', people=3658)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Małomice', people=3546)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Gozdnica', people=3334)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Dobiegniew', people=3169)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Nowe Miasteczko', people=2833)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Cybinka', people=2689)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Łęknica', people=2518)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Torzym', people=2462)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Trzciel', people=2318)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Lubniewice', people=1927)
		city.put()
		city = City(voivodeship=voivodeship.key(), name=u'Szlichtyngowa', people=1354)
		city.put()

		self.response.out.write(template.render('fill_db.html', {}))
	
def main():
	application = webapp.WSGIApplication([(r'.*', MainHandler)], debug=True)
	wsgiref.handlers.CGIHandler().run(application)

if __name__ == '__main__':
	main()
